{{- if eq .Values.storage.mode "create" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "minio") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
    app: {{ include "zymtrace.resourceName" (list $ "minio") }}
spec:
  serviceName: {{ include "zymtrace.resourceName" (list $ "minio") }}
  replicas: {{ .Values.storage.create.replicas }}
  selector:
    matchLabels:
      app: {{ include "zymtrace.resourceName" (list $ "minio") }}
  template:
    metadata:
      labels:
        app: {{ include "zymtrace.resourceName" (list $ "minio") }}
    spec:
      {{- include "zymtrace.dbNodeSelector" (list "storage" $) | nindent 6 }}
      {{- include "zymtrace.dbTolerations" (list "storage" $) | nindent 6 }}
      {{- include "zymtrace.dbAffinity" (list "storage" $) | nindent 6 }}
      containers:
        - name: {{ include "zymtrace.resourceName" (list $ "minio") }}
          image: "{{ include "database.imageRegistry" . }}{{ .Values.storage.create.image.repository }}:{{ .Values.storage.create.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          {{- include "zymtrace.resourceConfig" (list $ "storage") | nindent 10 }}
          args:
            - server
            - /data
            - --console-address
            - ":{{ .Values.storage.create.service.console.port }}"
          ports:
            - name: api
              containerPort: {{ .Values.storage.create.service.api.port }}
            - name: console
              containerPort: {{ .Values.storage.create.service.console.port }}
          {{- include "zymtrace.minioEnvConfig" . | nindent 10 }}
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - mc
                - ready
                - local
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - mc
                - ready
                - local
            initialDelaySeconds: 50
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: data
          {{- include "zymtrace.storage" (list $ "minio") | nindent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "minio") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      port: {{ .Values.storage.create.service.api.port }}
      targetPort: api
    - name: console
      port: {{ .Values.storage.create.service.console.port }}
      targetPort: console
  selector:
    app: {{ include "zymtrace.resourceName" (list $ "minio") }}

---
# MinIO bucket initialization job
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "minio-init") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
    app: {{ include "zymtrace.resourceName" (list $ "minio-init") }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"    
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 600  # 10 minutes
  template:
    metadata:
      labels:
        app: {{ include "zymtrace.resourceName" (list $ "minio-init") }}
    spec:
      {{- include "zymtrace.dbNodeSelector" (list "storage" $) | nindent 6 }}
      {{- include "zymtrace.dbTolerations" (list "storage" $) | nindent 6 }}
      {{- include "zymtrace.dbAffinity" (list "storage" $) | nindent 6 }}
      initContainers:
        - name: wait-for-minio
          image: "{{ include "database.imageRegistry" . }}{{ .Values.storage.create.image.repository }}:{{ .Values.storage.create.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              until mc alias set myminio http://{{ include "zymtrace.resourceName" (list $ "minio") }}:{{ .Values.storage.create.service.api.port }} "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"; do
                echo "Waiting for MinIO to be ready..."
                sleep 5
              done
          {{- include "zymtrace.minioEnvConfig" . | nindent 10 }}
      containers:
        - name: create-buckets
          image: "{{ include "database.imageRegistry" . }}{{ .Values.storage.create.image.repository }}:{{ .Values.storage.create.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio http://{{ include "zymtrace.resourceName" (list $ "minio") }}:{{ .Values.storage.create.service.api.port }} "${MINIO_ROOT_USER}" "${MINIO_ROOT_PASSWORD}"
              echo "Creating the symbols buckets..."
              mc mb myminio/{{ .Values.storage.buckets.symbols }} || echo "Bucket {{ .Values.storage.buckets.symbols }} already exists"
              echo "Bucket initialization completed"
          {{- include "zymtrace.minioEnvConfig" . | nindent 10 }}
      restartPolicy: OnFailure
{{- end }}