apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
    app: {{ include "zymtrace.resourceName" (list $ "web") }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"  # Higher weight than migration (1), ensures it runs after
    "helm.sh/hook-depends-on": {{ include "zymtrace.resourceName" (list $ "migrate") }}
spec:
  replicas: {{ .Values.services.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "zymtrace.resourceName" (list $ "web") }}
  template:
    metadata:
      labels:
        app: {{ include "zymtrace.resourceName" (list $ "web") }}
    spec:
      {{- include "zymtrace.nodeSelector" (list $ "web") | nindent 6 }}
      {{- include "zymtrace.tolerations" (list $ "web") | nindent 6 }}
      {{- include "zymtrace.affinity" (list $ "web") | nindent 6 }}
      {{- include "zymtrace.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ include "zymtrace.resourceName" (list $ "web") }}
          image: "{{ include "zymtrace.imageRegistry" . }}{{ include "zymtrace.repositoryName" (list $ "web") }}:{{ include "zymtrace.serviceTag" (list . "web") }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["zymtrace-web"]
          ports:
            - name: http
              containerPort: {{ .Values.services.web.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.services.web.resources | nindent 12 }}
          {{- include "zymtrace.serviceEnvConfig" (list $ "web") | nindent 10 }}
    
          {{- if include "zymtrace.livenessProbeEnabled" (list $ "web") }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: {{ .Values.services.web.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          {{- end }}
          {{- if include "zymtrace.readinessProbeEnabled" (list $ "web") }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: {{ .Values.services.web.port }}
            initialDelaySeconds: 10
            periodSeconds: 15
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
{{- if .Values.global.enableServiceMigration | default false }}
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "-1"
{{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "zymtrace.resourceName" (list $ "web") }}
---
{{- include "zymtrace.hpa" (list $ "web" .Values.services.web) }}