apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
    app: {{ include "zymtrace.resourceName" (list $ "web") }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"  # Higher weight than migration (1), ensures it runs after
    "helm.sh/hook-depends-on": {{ include "zymtrace.resourceName" (list $ "migrate") }}
spec:
  replicas: {{ .Values.services.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "zymtrace.resourceName" (list $ "web") }}
  template:
    metadata:
      labels:
        app: {{ include "zymtrace.resourceName" (list $ "web") }}
    spec:
      {{- include "zymtrace.nodeSelector" . | nindent 6 }}
      {{- include "zymtrace.tolerations" . | nindent 6 }}
      {{- include "zymtrace.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: {{ include "zymtrace.resourceName" (list $ "web") }}
          image: "{{ include "zymtrace.imageRegistry" . }}{{ include "zymtrace.repositoryName" (list $ "web") }}:{{ include "zymtrace.serviceTag" (list . "web") }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["zymtrace-web"]
          ports:
            - name: http
              containerPort: {{ .Values.services.web.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.services.web.resources | nindent 12 }}
          {{- include "zymtrace.envConfig" . | nindent 10 }}
    
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: http
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: http
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "web") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "zymtrace.resourceName" (list $ "web") }}
---
{{- include "zymtrace.hpa" (list $ "web" .Values.services.web) }}