{{- if include "zymtrace.useRegistrySecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "registry-cred") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
    app: {{ include "zymtrace.resourceName" (list $ "registry-cred") }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" 
    .Values.global.appImageRegistry
    .Values.global.registry.username
    .Values.global.registry.password
    (printf "%s:%s" .Values.global.registry.username .Values.global.registry.password | b64enc) 
    | b64enc 
  }}

{{- if not .Values.global.registry.username }}
{{- fail "\n\nRegistry username must be provided using:\n- Command line: --set global.registry.username=<username>\n- Values file: global.registry.username: <username>" }}
{{- end }}

{{- if not .Values.global.registry.password }}
{{- fail "\n\nRegistry password must be provided using:\n- Command line: --set global.registry.password=<password>\n- Values file: global.registry.password: <password>" }}
{{- end }}
{{- end }}