apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "auth-secrets") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  # License keys
  {{- if and .Values.global.licenseKey (not .Values.global.licenseKeySecretName) }}
  WEB__LICENSE__KEY: {{ .Values.global.licenseKey | quote }}
  INGEST__LICENSE__KEY: {{ .Values.global.licenseKey | quote }}
  {{- end }}

  # Basic auth credentials
  {{- if eq (include "zymtrace.authType" .) "basic" }}
  UI_USER: {{ .Values.auth.basic.username | quote }}
  UI_PASSWORD: {{ .Values.auth.basic.password | quote }}
  {{- end }}

  {{- if or (eq (include "zymtrace.authType" .) "oidc") (eq (include "zymtrace.authType" .) "local") }}
  # Admin credentials
  IDENTITY__AUTH__ADMIN__PASSWORD: {{ .Values.auth.admin.password | quote }}

  {{- $keys := .Values.auth.validation.keys }}
  {{- if and $keys.privateKey (not $keys.privateKeySecretName) }}
  # Token signing keys
  IDENTITY__AUTH__TOKEN__PRIVATE_KEY__CONTENT: |-
  {{ $keys.privateKey | nindent 4 }}
  {{- end }}
  {{- if and $keys.publicKey (not $keys.publicKeySecretName) }}
  IDENTITY__AUTH__TOKEN__PUBLIC_KEY__CONTENT: |-
  {{ $keys.publicKey | nindent 4 }}
  WEB__AUTH__VALIDATION__PUBLIC_KEY__CONTENT: |-
  {{ $keys.publicKey | nindent 4 }}
  {{- end }}
  {{- end }}

  {{- if eq (include "zymtrace.authType" .) "oidc" }}
  # OIDC client credentials
  IDENTITY__AUTH__OIDC__CLIENT_ID: {{ .Values.auth.oidc.provider.clientId | quote }}
  IDENTITY__AUTH__OIDC__CLIENT_SECRET: {{ .Values.auth.oidc.provider.clientSecret | quote }}
  {{- end }}
