apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "clickhouse-secrets") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.clickhouse.mode "create" }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.create.config.password | quote }}
  INGEST__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.create.config.password | quote }}
  #metrics
  INGEST__METRICS__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.create.config.password | quote }}

  WEB__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.create.config.password | quote }}
  WEB__METRICS__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.create.config.password | quote }}
  {{- else }}
  CLICKHOUSE_PASSWORD: {{ .Values.clickhouse.use_existing.password | quote }}
  INGEST__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.use_existing.password | quote }}

  #metrics
  INGEST__METRICS__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.use_existing.password | quote }}

  WEB__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.use_existing.password | quote }}
  WEB__METRICS__CLICKHOUSE__PASSWORD: {{ .Values.clickhouse.use_existing.password | quote }}
  {{- end }}
