{{- if .Values.services.gateway.mtls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "gateway-mtls") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
    app: {{ include "zymtrace.resourceName" (list $ "gateway") }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.services.gateway.mtls.cert | b64enc | quote }}
  tls.key: {{ .Values.services.gateway.mtls.key | b64enc | quote }}
  ca.crt: {{ .Values.services.gateway.mtls.ca | b64enc | quote }}
{{- end }}
