{{- if .Values.globalSymbolization.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "global-symbolization-secrets") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Global symbolization credentials
  {{- if .Values.globalSymbolization.config.accessKey }}
  SYMDB__GLOBAL_SYM_ENDPOINT__AWS_ACCESS_KEY_ID: {{ .Values.globalSymbolization.config.accessKey | quote }}
  {{- end }}
  {{- if .Values.globalSymbolization.config.secretKey }}
  SYMDB__GLOBAL_SYM_ENDPOINT__AWS_SECRET_ACCESS_KEY: {{ .Values.globalSymbolization.config.secretKey | quote }}
  {{- end }}
{{- end }}
