{{- if eq .Values.storage.mode "create" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "minio-secrets") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.storage.create.config.user | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.storage.create.config.password | quote }}
{{- end }}
