apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "storage-secrets") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.storage.mode "create" }}
  SYMDB__SYMBOL_BUCKET__AWS_ACCESS_KEY_ID: {{ .Values.storage.create.config.user | quote }}
  SYMDB__SYMBOL_BUCKET__AWS_SECRET_ACCESS_KEY: {{ .Values.storage.create.config.password | quote }}
  {{- else if eq .Values.storage.use_existing.type "minio" }}
  SYMDB__SYMBOL_BUCKET__AWS_ACCESS_KEY_ID: {{ .Values.storage.use_existing.minio.user | quote }}
  SYMDB__SYMBOL_BUCKET__AWS_SECRET_ACCESS_KEY: {{ .Values.storage.use_existing.minio.password | quote }}
  {{- else if eq .Values.storage.use_existing.type "s3" }}
  SYMDB__SYMBOL_BUCKET__AWS_ACCESS_KEY_ID: {{ .Values.storage.use_existing.s3.accessKey | quote }}
  SYMDB__SYMBOL_BUCKET__AWS_SECRET_ACCESS_KEY: {{ .Values.storage.use_existing.s3.secretKey | quote }}
  {{- if .Values.storage.use_existing.s3.sessionToken }}
  SYMDB__SYMBOL_BUCKET__AWS_SESSION_TOKEN: {{ .Values.storage.use_existing.s3.sessionToken | quote }}
  {{- end }}
  {{- else if eq .Values.storage.use_existing.type "gcs" }}
  SYMDB__SYMBOL_BUCKET__AWS_ACCESS_KEY_ID: {{ .Values.storage.use_existing.gcs.accessKey | quote }}
  SYMDB__SYMBOL_BUCKET__AWS_SECRET_ACCESS_KEY: {{ .Values.storage.use_existing.gcs.secretKey | quote }}
  {{- end }}
