{{- if include "zymtrace.profiler.useOwnAuthTokenSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list . "profiler-auth-token") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ .Values.profiler.authToken.value | b64enc }}
{{- end }}
