{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zymtrace.resourceName" (list . "profiler") }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zymtrace.resourceName" (list . "profiler") }}-{{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zymtrace.resourceName" (list . "profiler") }}-{{ .Release.Namespace }}-v2
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "zymtrace.resourceName" (list . "profiler") }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "zymtrace.resourceName" (list . "profiler") }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
