{{- if include "zymtrace.useRegistrySecret" . }}
{{- if not .Values.global.registry.username }}
{{- fail "\n\nRegistry username must be provided using:\n- Command line: --set global.registry.username=<username>\n- Values file: global.registry.username: <username>" }}
{{- end }}

{{- if not .Values.global.registry.password }}
{{- fail "\n\nRegistry password must be provided using:\n- Command line: --set global.registry.password=<password>\n- Values file: global.registry.password: <password>" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "registry-cred-profiler") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" 
    .Values.global.imageRegistry 
    .Values.global.registry.username
    .Values.global.registry.password
    (printf "%s:%s" .Values.global.registry.username .Values.global.registry.password | b64enc) 
    | b64enc 
  }}
{{- end }}