{{- if and .Values.ingress.enabled .Values.services.gateway.mtls.enabled .Values.ingress.hosts.gateway.mtls.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zymtrace.resourceName" (list $ "gateway-ingress-mtls") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zymtrace.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-failed"
    "helm.sh/hook-depends-on": "{{ include "zymtrace.resourceName" (list $ "gateway") }}"
    "helm.sh/resource-policy": "keep"
    {{- if eq .Values.ingress.className "nginx" }}
    # Automatically add HTTP/2 and gRPC support for Nginx ingress
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/http2-enable: "true"
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.hosts.gateway.mtls.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.gateway.mtls.host | quote }}
      http:
        paths:
            {{- range .Values.ingress.hosts.gateway.mtls.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "zymtrace.resourceName" (list $ "gateway") }}
                port:
                  number: {{ $.Values.services.gateway.mtls.port }}
            {{- end }}
{{- end }}
